sudo: required

services:
  - docker

install:
  - gem install awesome_bot
  - export HUGO_LATEST_URL=$(curl --silent --location https://api.github.com/repos/spf13/hugo/releases/latest | awk -F \" '/browser_download_url.*Linux-64bit.tar.gz/ { print $4 }')
  - echo "$HUGO_LATEST_URL"
  - if [ -z "$HUGO_LATEST_URL" ]; then curl --verbose --location https://api.github.com/repos/spf13/hugo/releases/latest; fi
  - curl --silent --location $HUGO_LATEST_URL | sudo tar xvzf - -C /usr/local/bin/ hugo
  - rm -rf public || exit 0

script:
  - export HOST_IP_ADDRESS="$(ip -4 addr show docker0 | sed -n 's/.* inet \([^/]*\).*/\1/p')"
  - hugo server --bind ${HOST_IP_ADDRESS} --baseURL http://${TRAVIS_REPO_SLUG##*/} &
  - docker run -it --rm --add-host ${TRAVIS_REPO_SLUG##*/}:${HOST_IP_ADDRESS} linkchecker/linkchecker --check-extern http://${TRAVIS_REPO_SLUG##*/}:1313
  - awesome_bot --allow-dupe --allow-redirect --skip-save-results `find . -name *.md`
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  fqdn: ${TRAVIS_REPO_SLUG##*/}
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
