name: hugo-build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  hugo-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: |
          hugo --gc
          cp LICENSE README.md public/

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ steps.pages.outputs.base_url }}
          pages_path: public
          cmd_params: '--exclude=(linkedin.com|html5up.net|pixabay.com|instagram.com) --buffer-size=8192 --max-connections-per-host=5 --color=always --rate-limit=5 --header="User-Agent:curl/7.54.0" --skip-tls-verification'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: ${{ steps.pages.outputs.host }}
