name: Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/links.yml
      - lychee.toml

permissions: read-all

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Restore lychee cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@v1
        with:
          args: ". --exclude-path CHANGELOG.md ${{ steps.pages.outputs.base_url }}"
          fail: true
